// Real Banalata Resort menu (curated from https://banalataresort.com/restaurant-cafe/)
// en/hi/bn names, full & half prices in INR, per-plate quantity notes.

export const CATEGORIES = [
  { id: "breakfast",  en: "Breakfast",         hi: "नाश्ता",         bn: "প্রাতরাশ" },
  { id: "starter",    en: "Starters",          hi: "स्टार्टर",       bn: "স্টার্টার" },
  { id: "tandoor",    en: "Tandoor",           hi: "तंदूर",          bn: "তন্দুর" },
  { id: "bengali",    en: "Banalata Bengali",  hi: "बंगाली स्पेशल",  bn: "বনলতা বাংলা" },
  { id: "chicken",    en: "Chicken",           hi: "चिकन",           bn: "চিকেন" },
  { id: "mutton",     en: "Mutton",            hi: "मटन",            bn: "মটন" },
  { id: "fish",       en: "Fish",              hi: "मछली",           bn: "মাছ" },
  { id: "chinese",    en: "Chinese",           hi: "चाइनीज़",        bn: "চাইনিজ" },
  { id: "veg",        en: "Indian Veg",        hi: "इंडियन वेज",     bn: "ইন্ডিয়ান ভেজ" },
  { id: "rice",       en: "Rice & Biryani",    hi: "चावल",           bn: "ভাত ও বিরিয়ানি" },
  { id: "bread",      en: "Roti / Paratha",    hi: "रोटी / पराठा",   bn: "রুটি / পরোটা" },
  { id: "dessert",    en: "Dessert",           hi: "मिठाई",          bn: "মিষ্টি" },
  { id: "mocktail",   en: "Mocktail & Drinks", hi: "मॉकटेल",         bn: "মকটেল ও পানীয়" },
  { id: "extras",     en: "Extras",            hi: "अतिरिक्त",       bn: "অতিরিক্ত" },
];

// price = full plate price. half = half-plate (null if only full).
// qty = quantity per FULL plate description in 3 langs.
export const ITEMS = [
  // ---------- BREAKFAST ----------
  { id:"b01", cat:"breakfast", price:140, half:null,
    en:{name:"Matorshutir Kachuri with Cholar Dal", qty:"4 kachuri + 1 bowl dal"},
    hi:{name:"मटर कचौड़ी + चोलार दाल",              qty:"4 कचौड़ी + 1 कटोरी दाल"},
    bn:{name:"মটরশুঁটির কচুরি + ছোলার ডাল",        qty:"৪টি কচুরি + ১ বাটি ডাল"} },
  { id:"b02", cat:"breakfast", price:80, half:null,
    en:{name:"Puri Sabji", qty:"4 puri + curry bowl"},
    hi:{name:"पूरी सब्ज़ी", qty:"4 पूरी + सब्ज़ी"},
    bn:{name:"পুরি সবজি", qty:"৪টি পুরি + সবজি"} },
  { id:"b03", cat:"breakfast", price:130, half:null,
    en:{name:"Egg Sandwich", qty:"4 pieces"},
    hi:{name:"एग सैंडविच", qty:"4 पीस"},
    bn:{name:"ডিমের স্যান্ডউইচ", qty:"৪ পিস"} },
  { id:"b04", cat:"breakfast", price:140, half:null,
    en:{name:"Chicken Sandwich", qty:"4 pieces"},
    hi:{name:"चिकन सैंडविच", qty:"4 पीस"},
    bn:{name:"চিকেন স্যান্ডউইচ", qty:"৪ পিস"} },
  { id:"b05", cat:"breakfast", price:120, half:null,
    en:{name:"Butter Toast", qty:"6 pieces"},
    hi:{name:"बटर टोस्ट", qty:"6 पीस"},
    bn:{name:"বাটার টোস্ট", qty:"৬ পিস"} },

  // ---------- STARTERS ----------
  { id:"s01", cat:"starter", price:320, half:200,
    en:{name:"Fish Finger", qty:"4 pieces + salad + dip"},
    hi:{name:"फिश फिंगर", qty:"4 पीस + सलाद + डिप"},
    bn:{name:"ফিশ ফিঙ্গার", qty:"৪ পিস + সালাদ + ডিপ"} },
  { id:"s02", cat:"starter", price:80, half:null,
    en:{name:"Potato Chop", qty:"4 pieces + kasundi"},
    hi:{name:"आलू चॉप", qty:"4 पीस + कसुंदी"},
    bn:{name:"আলুর চপ", qty:"৪ পিস + কাসুন্দি"} },
  { id:"s03", cat:"starter", price:220, half:null,
    en:{name:"Cheese Ball", qty:"6 pieces"},
    hi:{name:"चीज़ बॉल", qty:"6 पीस"},
    bn:{name:"চিজ় বল", qty:"৬ পিস"} },
  { id:"s04", cat:"starter", price:60, half:null,
    en:{name:"Masala Papad", qty:"1 piece"},
    hi:{name:"मसाला पापड़", qty:"1 पीस"},
    bn:{name:"মশলা পাপড়", qty:"১ পিস"} },
  { id:"s05", cat:"starter", price:100, half:null,
    en:{name:"Fruit Chart", qty:"1 plate (~200 g)"},
    hi:{name:"फ्रूट चाट", qty:"1 प्लेट (~200 g)"},
    bn:{name:"ফ্রুট চাট", qty:"১ প্লেট (~২০০ গ্রাম)"} },

  // ---------- TANDOOR ----------
  { id:"t01", cat:"tandoor", price:400, half:null,
    en:{name:"Chicken Tandoori (Full)", qty:"1 full bird, 4 pcs"},
    hi:{name:"चिकन तंदूरी (फुल)", qty:"1 पूरा, 4 पीस"},
    bn:{name:"চিকেন তন্দুরি (ফুল)", qty:"১ ফুল, ৪ পিস"} },
  { id:"t02", cat:"tandoor", price:260, half:null,
    en:{name:"Chicken Reshmi Kebab", qty:"6 pieces"},
    hi:{name:"चिकन रेशमी कबाब", qty:"6 पीस"},
    bn:{name:"চিকেন রেশমি কাবাব", qty:"৬ পিস"} },
  { id:"t03", cat:"tandoor", price:260, half:null,
    en:{name:"Chicken Pudina Tikka", qty:"6 pieces + onion + chutney"},
    hi:{name:"चिकन पुदीना टिक्का", qty:"6 पीस + प्याज़ + चटनी"},
    bn:{name:"চিকেন পুদিনা টিক্কা", qty:"৬ পিস + পিঁয়াজ + চাটনি"} },
  { id:"t04", cat:"tandoor", price:310, half:null,
    en:{name:"Chicken Leg Kabab", qty:"2 legs"},
    hi:{name:"चिकन लेग कबाब", qty:"2 पीस"},
    bn:{name:"চিকেন লেগ কাবাব", qty:"২ পিস"} },

  // ---------- BANALATA BENGALI ----------
  { id:"be01", cat:"bengali", price:450, half:null,
    en:{name:"Special Veg Thali", qty:"Rice, dal, 3 sabji, chutney, papad, sweet"},
    hi:{name:"स्पेशल वेज थाली", qty:"चावल, दाल, 3 सब्ज़ी, चटनी, पापड़, मिठाई"},
    bn:{name:"স্পেশাল ভেজ থালি", qty:"ভাত, ডাল, ৩ সবজি, চাটনি, পাপড়, মিষ্টি"} },
  { id:"be02", cat:"bengali", price:300, half:null,
    en:{name:"Tribal Mutton Thali", qty:"Rice + aloo chokha + mutton 2 pcs + chutney"},
    hi:{name:"ट्राइबल मटन थाली", qty:"चावल + आलू चोखा + मटन 2 पीस + चटनी"},
    bn:{name:"ট্রাইবাল মটন থালি", qty:"ভাত + আলু চোখা + মটন ২ পিস + চাটনি"} },
  { id:"be03", cat:"bengali", price:200, half:null,
    en:{name:"Tribal Chicken Thali", qty:"Rice + aloo chokha + chicken 2 pcs + chutney"},
    hi:{name:"ट्राइबल चिकन थाली", qty:"चावल + आलू चोखा + चिकन 2 पीस + चटनी"},
    bn:{name:"ট্রাইবাল চিকেন থালি", qty:"ভাত + আলু চোখা + চিকেন ২ পিস + চাটনি"} },
  { id:"be04", cat:"bengali", price:350, half:null,
    en:{name:"Vetki Paturi (Sal-leaf)", qty:"2 pieces wrapped"},
    hi:{name:"भेटकी पातुरी (साल पत्ता)", qty:"2 पीस"},
    bn:{name:"ভেটকি পাতুরি (শাল পাতা)", qty:"২ পিস"} },
  { id:"be05", cat:"bengali", price:100, half:null,
    en:{name:"Muri Ghonto", qty:"1 bowl"},
    hi:{name:"मुड़ी घंटो", qty:"1 कटोरी"},
    bn:{name:"মুড়ি ঘন্ট", qty:"১ বাটি"} },
  { id:"be06", cat:"bengali", price:340, half:180,
    en:{name:"Kadaknath Chicken Kosha", qty:"4 pieces + gravy"},
    hi:{name:"कड़कनाथ चिकन कोशा", qty:"4 पीस + ग्रेवी"},
    bn:{name:"কড়কনাথ চিকেন কষা", qty:"৪ পিস + গ্রেভি"} },
  { id:"be07", cat:"bengali", price:350, half:200,
    en:{name:"Emu Kosha", qty:"6 pieces + gravy"},
    hi:{name:"ईमू कोशा", qty:"6 पीस + ग्रेवी"},
    bn:{name:"ইমু কষা", qty:"৬ পিস + গ্রেভি"} },
  { id:"be08", cat:"bengali", price:300, half:200,
    en:{name:"Turkey Kosha", qty:"4 pieces + gravy"},
    hi:{name:"टर्की कोशा", qty:"4 पीस + ग्रेवी"},
    bn:{name:"টার্কি কষা", qty:"৪ পিস + গ্রেভি"} },
  { id:"be09", cat:"bengali", price:200, half:120,
    en:{name:"Duck Kosha", qty:"4 pieces + gravy"},
    hi:{name:"डक कोशा", qty:"4 पीस + ग्रेवी"},
    bn:{name:"হাঁসের কষা", qty:"৪ পিস + গ্রেভি"} },

  // ---------- CHICKEN ----------
  { id:"c01", cat:"chicken", price:250, half:200,
    en:{name:"Chicken Butter Masala", qty:"4 pieces + gravy"},
    hi:{name:"चिकन बटर मसाला", qty:"4 पीस + ग्रेवी"},
    bn:{name:"চিকেন বাটার মশলা", qty:"৪ পিস + গ্রেভি"} },
  { id:"c02", cat:"chicken", price:180, half:100,
    en:{name:"Chicken Kosha", qty:"4 pieces + gravy"},
    hi:{name:"चिकन कोशा", qty:"4 पीस + ग्रेवी"},
    bn:{name:"চিকেন কষা", qty:"৪ পিস + গ্রেভি"} },
  { id:"c03", cat:"chicken", price:260, half:190,
    en:{name:"Chicken Do Piyaza", qty:"4 pieces + onion gravy"},
    hi:{name:"चिकन दो प्याज़ा", qty:"4 पीस + प्याज़ ग्रेवी"},
    bn:{name:"চিকেন দো পিঁয়াজি", qty:"৪ পিস + পিঁয়াজের গ্রেভি"} },
  { id:"c04", cat:"chicken", price:350, half:null,
    en:{name:"Chicken Chaap (Slow Cooked)", qty:"2 pieces (leg)"},
    hi:{name:"चिकन चाप (धीमी आँच)", qty:"2 पीस (लेग)"},
    bn:{name:"চিকেন চাপ (স্লো কুকড)", qty:"২ পিস (লেগ)"} },
  { id:"c05", cat:"chicken", price:280, half:190,
    en:{name:"Chicken Reshmi Butter Masala", qty:"4 pieces + creamy gravy"},
    hi:{name:"चिकन रेशमी बटर मसाला", qty:"4 पीस + क्रीमी ग्रेवी"},
    bn:{name:"চিকেন রেশমি বাটার মশলা", qty:"৪ পিস + ক্রিমি গ্রেভি"} },

  // ---------- MUTTON ----------
  { id:"m01", cat:"mutton", price:360, half:200,
    en:{name:"Mutton Kosha", qty:"4 pieces + thick gravy"},
    hi:{name:"मटन कोशा", qty:"4 पीस + गाढ़ी ग्रेवी"},
    bn:{name:"মটন কষা", qty:"৪ পিস + ঘন গ্রেভি"} },
  { id:"m02", cat:"mutton", price:420, half:300,
    en:{name:"Mutton Do Piyaza", qty:"4 pieces + onion gravy"},
    hi:{name:"मटन दो प्याज़ा", qty:"4 पीस + प्याज़ ग्रेवी"},
    bn:{name:"মটন দো পিঁয়াজি", qty:"৪ পিস + পিঁয়াজের গ্রেভি"} },
  { id:"m03", cat:"mutton", price:450, half:null,
    en:{name:"Mutton Mete Chorchori", qty:"1 bowl (~250 g)"},
    hi:{name:"मटन मेटे चोरचोरी", qty:"1 कटोरी (~250 g)"},
    bn:{name:"মটন মেটে চচ্চড়ি", qty:"১ বাটি (~২৫০ গ্রাম)"} },
  { id:"m04", cat:"mutton", price:550, half:300,
    en:{name:"Mutton Keema", qty:"1 bowl (~250 g) + peas"},
    hi:{name:"मटन कीमा", qty:"1 कटोरी (~250 g) + मटर"},
    bn:{name:"মটন কিমা", qty:"১ বাটি (~২৫০ গ্রাম) + মটর"} },

  // ---------- FISH ----------
  { id:"f01", cat:"fish", price:500, half:null,
    en:{name:"Dub Hilsa (Young Coconut Ilish)", qty:"2 pieces in coconut"},
    hi:{name:"डाब हिलसा", qty:"2 पीस नारियल में"},
    bn:{name:"ডাব ইলিশ", qty:"২ পিস ডাবের মধ্যে"} },
  { id:"f02", cat:"fish", price:500, half:null,
    en:{name:"Hilsa Paturi", qty:"2 pieces wrapped"},
    hi:{name:"हिलसा पातुरी", qty:"2 पीस"},
    bn:{name:"ইলিশ পাতুরি", qty:"২ পিস"} },
  { id:"f03", cat:"fish", price:450, half:null,
    en:{name:"Desi Koi", qty:"2 pieces + gravy"},
    hi:{name:"देसी कोई", qty:"2 पीस + ग्रेवी"},
    bn:{name:"দেশি কই", qty:"২ পিস + গ্রেভি"} },
  { id:"f04", cat:"fish", price:320, half:null,
    en:{name:"Vetki Fish Masala", qty:"2 pieces + gravy"},
    hi:{name:"भेटकी फिश मसाला", qty:"2 पीस + ग्रेवी"},
    bn:{name:"ভেটকি মশলা", qty:"২ পিস + গ্রেভি"} },
  { id:"f05", cat:"fish", price:220, half:null,
    en:{name:"Rui Posto", qty:"2 pieces + poppyseed gravy"},
    hi:{name:"रुई पोस्तो", qty:"2 पीस + पोस्तो ग्रेवी"},
    bn:{name:"রুই পোস্ত", qty:"২ পিস + পোস্ত গ্রেভি"} },
  { id:"f06", cat:"fish", price:380, half:null,
    en:{name:"Pomfret Sarse Bata", qty:"1 whole pomfret + mustard"},
    hi:{name:"पॉम्फ्रेट सरसों", qty:"1 पूरा + सरसों"},
    bn:{name:"পমফ্রেট সরষে বাটা", qty:"১ গোটা + সরষে"} },

  // ---------- CHINESE ----------
  { id:"ch01", cat:"chinese", price:200, half:120,
    en:{name:"Chilli Chicken", qty:"4 pieces + capsicum"},
    hi:{name:"चिली चिकन", qty:"4 पीस + शिमला"},
    bn:{name:"চিলি চিকেন", qty:"৪ পিস + ক্যাপসিকাম"} },
  { id:"ch02", cat:"chinese", price:200, half:120,
    en:{name:"Garlic Chicken", qty:"4 pieces + garlic sauce"},
    hi:{name:"गार्लिक चिकन", qty:"4 पीस + लहसुन सॉस"},
    bn:{name:"গার্লিক চিকেন", qty:"৪ পিস + রসুন সস"} },
  { id:"ch03", cat:"chinese", price:200, half:120,
    en:{name:"Chicken Manchurian", qty:"4 pieces + gravy"},
    hi:{name:"चिकन मंचूरियन", qty:"4 पीस + ग्रेवी"},
    bn:{name:"চিকেন মাঞ্চুরিয়ান", qty:"৪ পিস + গ্রেভি"} },
  { id:"ch04", cat:"chinese", price:200, half:120,
    en:{name:"Schezwan Chicken", qty:"4 pieces + schezwan"},
    hi:{name:"शेज़वान चिकन", qty:"4 पीस + शेज़वान"},
    bn:{name:"শেজওয়ান চিকেন", qty:"৪ পিস + শেজওয়ান"} },
  { id:"ch05", cat:"chinese", price:200, half:120,
    en:{name:"Chilli Fish", qty:"4 pieces (~200 g)"},
    hi:{name:"चिली फिश", qty:"4 पीस (~200 g)"},
    bn:{name:"চিলি ফিশ", qty:"৪ পিস (~২০০ গ্রাম)"} },
  { id:"ch06", cat:"chinese", price:220, half:140,
    en:{name:"Mixed Fried Rice", qty:"1 plate (~350 g)"},
    hi:{name:"मिक्स्ड फ्राइड राइस", qty:"1 प्लेट (~350 g)"},
    bn:{name:"মিক্সড ফ্রায়েড রাইস", qty:"১ প্লেট (~৩৫০ গ্রাম)"} },
  { id:"ch07", cat:"chinese", price:180, half:110,
    en:{name:"Chicken Fried Rice", qty:"1 plate (~350 g)"},
    hi:{name:"चिकन फ्राइड राइस", qty:"1 प्लेट (~350 g)"},
    bn:{name:"চিকেন ফ্রায়েড রাইস", qty:"১ প্লেট (~৩৫০ গ্রাম)"} },
  { id:"ch08", cat:"chinese", price:140, half:90,
    en:{name:"Egg Fried Rice", qty:"1 plate (~300 g)"},
    hi:{name:"अंडा फ्राइड राइस", qty:"1 प्लेट (~300 g)"},
    bn:{name:"ডিম ফ্রায়েড রাইস", qty:"১ প্লেট (~৩০০ গ্রাম)"} },
  { id:"ch09", cat:"chinese", price:320, half:210,
    en:{name:"Mixed Chowmein", qty:"1 plate (~350 g)"},
    hi:{name:"मिक्स्ड चौमीन", qty:"1 प्लेट (~350 g)"},
    bn:{name:"মিক্সড চাউমিন", qty:"১ প্লেট (~৩৫০ গ্রাম)"} },
  { id:"ch10", cat:"chinese", price:140, half:90,
    en:{name:"Chicken Chowmein", qty:"1 plate (~300 g)"},
    hi:{name:"चिकन चौमीन", qty:"1 प्लेट (~300 g)"},
    bn:{name:"চিকেন চাউমিন", qty:"১ প্লেট (~৩০০ গ্রাম)"} },

  // ---------- INDIAN VEG ----------
  { id:"v01", cat:"veg", price:320, half:null,
    en:{name:"Paneer Tikka Masala", qty:"6 cubes + gravy"},
    hi:{name:"पनीर टिक्का मसाला", qty:"6 पीस + ग्रेवी"},
    bn:{name:"পনির টিক্কা মশলা", qty:"৬ পিস + গ্রেভি"} },
  { id:"v02", cat:"veg", price:250, half:170,
    en:{name:"Shahi Paneer", qty:"6 cubes + creamy gravy"},
    hi:{name:"शाही पनीर", qty:"6 पीस + क्रीमी ग्रेवी"},
    bn:{name:"শাহি পনির", qty:"৬ পিস + ক্রিমি গ্রেভি"} },
  { id:"v03", cat:"veg", price:300, half:200,
    en:{name:"Kaju Paneer (Cashew Gravy)", qty:"6 cubes + cashew gravy"},
    hi:{name:"काजू पनीर", qty:"6 पीस + काजू ग्रेवी"},
    bn:{name:"কাজু পনির", qty:"৬ পিস + কাজু গ্রেভি"} },
  { id:"v04", cat:"veg", price:230, half:150,
    en:{name:"Mushroom Masala", qty:"1 bowl (~200 g)"},
    hi:{name:"मशरूम मसाला", qty:"1 कटोरी (~200 g)"},
    bn:{name:"মাশরুম মশলা", qty:"১ বাটি (~২০০ গ্রাম)"} },
  { id:"v05", cat:"veg", price:180, half:100,
    en:{name:"Navaratna Korma", qty:"1 bowl mixed veg + nuts"},
    hi:{name:"नवरतन कोरमा", qty:"1 कटोरी मिक्स्ड वेज + मेवा"},
    bn:{name:"নবরত্ন কোরমা", qty:"১ বাটি মিক্সড ভেজ + বাদাম"} },
  { id:"v06", cat:"veg", price:120, half:80,
    en:{name:"Veg Kadai", qty:"1 bowl (~200 g)"},
    hi:{name:"वेज कड़ाई", qty:"1 कटोरी (~200 g)"},
    bn:{name:"ভেজ কড়াই", qty:"১ বাটি (~২০০ গ্রাম)"} },
  { id:"v07", cat:"veg", price:80, half:null,
    en:{name:"Dal Fry", qty:"1 bowl (~250 ml)"},
    hi:{name:"दाल फ्राई", qty:"1 कटोरी (~250 ml)"},
    bn:{name:"ডাল ফ্রাই", qty:"১ বাটি (~২৫০ মিলি)"} },

  // ---------- RICE & BIRYANI ----------
  { id:"r01", cat:"rice", price:120, half:null,
    en:{name:"Rice Thali (Bhat, Dal, 2 Sabji, Chutney)", qty:"1 thali"},
    hi:{name:"राइस थाली", qty:"1 थाली"},
    bn:{name:"রাইস থালি (ভাত, ডাল, ২ সবজি, চাটনি)", qty:"১ থালি"} },
  { id:"r02", cat:"rice", price:400, half:null,
    en:{name:"Egg Chicken Khichuri (Gobindobhog)", qty:"1 plate (~450 g)"},
    hi:{name:"अंडा चिकन खिचड़ी (गोबिन्दोभोग)", qty:"1 प्लेट (~450 g)"},
    bn:{name:"ডিম চিকেন খিচুড়ি (গোবিন্দভোগ)", qty:"১ প্লেট (~৪৫০ গ্রাম)"} },
  { id:"r03", cat:"rice", price:360, half:null,
    en:{name:"Chicken Khichdi (Gobindobhog)", qty:"1 plate (~400 g)"},
    hi:{name:"चिकन खिचड़ी", qty:"1 प्लेट (~400 g)"},
    bn:{name:"চিকেন খিচুড়ি", qty:"১ প্লেট (~৪০০ গ্রাম)"} },
  { id:"r04", cat:"rice", price:200, half:null,
    en:{name:"Veg Khichdi Plain", qty:"1 plate (~350 g)"},
    hi:{name:"वेज खिचड़ी प्लेन", qty:"1 प्लेट (~350 g)"},
    bn:{name:"ভেজ খিচুড়ি প্লেন", qty:"১ প্লেট (~৩৫০ গ্রাম)"} },

  // ---------- BREAD ----------
  { id:"br01", cat:"bread", price:30, half:null,
    en:{name:"Tawa Paratha", qty:"1 piece"},
    hi:{name:"तवा पराठा", qty:"1 पीस"},
    bn:{name:"তাওয়া পরোটা", qty:"১ পিস"} },
  { id:"br02", cat:"bread", price:50, half:null,
    en:{name:"Masala Paratha", qty:"1 piece"},
    hi:{name:"मसाला पराठा", qty:"1 पीस"},
    bn:{name:"মশলা পরোটা", qty:"১ পিস"} },
  { id:"br03", cat:"bread", price:60, half:null,
    en:{name:"Aloo Paratha", qty:"1 stuffed"},
    hi:{name:"आलू पराठा", qty:"1 भरा"},
    bn:{name:"আলু পরোটা", qty:"১ স্টাফড"} },
  { id:"br04", cat:"bread", price:50, half:null,
    en:{name:"Egg Paratha", qty:"1 piece"},
    hi:{name:"एग पराठा", qty:"1 पीस"},
    bn:{name:"ডিম পরোটা", qty:"১ পিস"} },
  { id:"br05", cat:"bread", price:50, half:null,
    en:{name:"Gobi Paratha", qty:"1 piece"},
    hi:{name:"गोबी पराठा", qty:"1 पीस"},
    bn:{name:"গোবি পরোটা", qty:"১ পিস"} },

  // ---------- DESSERT ----------
  { id:"d01", cat:"dessert", price:100, half:60,
    en:{name:"Mishti Doi (Sweet Curd)", qty:"1 bhaar (~150 g)"},
    hi:{name:"मिष्टी दोई", qty:"1 भाड़ (~150 g)"},
    bn:{name:"মিষ্টি দই", qty:"১ ভাঁড় (~১৫০ গ্রাম)"} },
  { id:"d02", cat:"dessert", price:80, half:50,
    en:{name:"Tok Doi (Sour Curd)", qty:"1 bhaar (~150 g)"},
    hi:{name:"तोक दोई", qty:"1 भाड़ (~150 g)"},
    bn:{name:"টক দই", qty:"১ ভাঁড় (~১৫০ গ্রাম)"} },
  { id:"d03", cat:"dessert", price:200, half:null,
    en:{name:"Malai", qty:"1 bowl"},
    hi:{name:"मलाई", qty:"1 कटोरी"},
    bn:{name:"মালাই", qty:"১ বাটি"} },
  { id:"d04", cat:"dessert", price:80, half:null,
    en:{name:"Kheer", qty:"1 bowl (~200 ml)"},
    hi:{name:"खीर", qty:"1 कटोरी (~200 ml)"},
    bn:{name:"ক্ষীর", qty:"১ বাটি (~২০০ মিলি)"} },
  { id:"d05", cat:"dessert", price:60, half:null,
    en:{name:"Desi Ghee Lancha", qty:"1 piece"},
    hi:{name:"देसी घी लंगचा", qty:"1 पीस"},
    bn:{name:"দেশি ঘি ল্যাংচা", qty:"১ পিস"} },
  { id:"d06", cat:"dessert", price:40, half:null,
    en:{name:"Rajbhog", qty:"1 piece"},
    hi:{name:"राजभोग", qty:"1 पीस"},
    bn:{name:"রাজভোগ", qty:"১ পিস"} },

  // ---------- MOCKTAIL & DRINKS ----------
  { id:"dr01", cat:"mocktail", price:80, half:null,
    en:{name:"Virgin Mojito", qty:"1 glass (~300 ml)"},
    hi:{name:"वर्जिन मोहितो", qty:"1 गिलास (~300 ml)"},
    bn:{name:"ভার্জিন মোহিতো", qty:"১ গ্লাস (~৩০০ মিলি)"} },
  { id:"dr02", cat:"mocktail", price:80, half:null,
    en:{name:"Pan Mojito", qty:"1 glass (~300 ml)"},
    hi:{name:"पान मोहितो", qty:"1 गिलास (~300 ml)"},
    bn:{name:"পান মোহিতো", qty:"১ গ্লাস (~৩০০ মিলি)"} },
  { id:"dr03", cat:"mocktail", price:100, half:null,
    en:{name:"Pina Colada", qty:"1 glass (~300 ml)"},
    hi:{name:"पिना कोलाडा", qty:"1 गिलास (~300 ml)"},
    bn:{name:"পিনা কোলাডা", qty:"১ গ্লাস (~৩০০ মিলি)"} },
  { id:"dr04", cat:"mocktail", price:100, half:null,
    en:{name:"Mango Tango", qty:"1 glass (~300 ml)"},
    hi:{name:"मैंगो टैंगो", qty:"1 गिलास (~300 ml)"},
    bn:{name:"ম্যাংগো ট্যাংগো", qty:"১ গ্লাস (~৩০০ মিলি)"} },
  { id:"dr05", cat:"mocktail", price:40, half:null,
    en:{name:"Coke (Bottle)", qty:"1 bottle 300 ml + straw"},
    hi:{name:"कोक (बोतल)", qty:"1 बोतल 300 ml + स्ट्रॉ"},
    bn:{name:"কোক (বোতল)", qty:"১ বোতল ৩০০ মিলি + স্ট্র"} },
  { id:"dr06", cat:"mocktail", price:30, half:null,
    en:{name:"Milk Tea", qty:"1 cup (~150 ml)"},
    hi:{name:"दूध चाय", qty:"1 कप (~150 ml)"},
    bn:{name:"দুধ চা", qty:"১ কাপ (~১৫০ মিলি)"} },
  { id:"dr07", cat:"mocktail", price:60, half:null,
    en:{name:"Milk Coffee", qty:"1 cup (~150 ml)"},
    hi:{name:"मिल्क कॉफ़ी", qty:"1 कप (~150 ml)"},
    bn:{name:"মিল্ক কফি", qty:"১ কাপ (~১৫০ মিলি)"} },
  { id:"dr08", cat:"mocktail", price:20, half:null,
    en:{name:"Green Tea", qty:"1 cup (~150 ml)"},
    hi:{name:"ग्रीन टी", qty:"1 कप (~150 ml)"},
    bn:{name:"গ্রিন টি", qty:"১ কাপ (~১৫০ মিলি)"} },

  // ---------- EXTRAS ----------
  { id:"x01", cat:"extras", price:10, half:null,
    en:{name:"Extra Plate", qty:"1 empty plate"},
    hi:{name:"एक्स्ट्रा प्लेट", qty:"1 खाली प्लेट"},
    bn:{name:"এক্সট্রা প্লেট", qty:"১ খালি প্লেট"} },
  { id:"x02", cat:"extras", price:5, half:null,
    en:{name:"Extra Spoon", qty:"1 spoon"},
    hi:{name:"एक्स्ट्रा चम्मच", qty:"1 चम्मच"},
    bn:{name:"এক্সট্রা চামচ", qty:"১ চামচ"} },
  { id:"x03", cat:"extras", price:2, half:null,
    en:{name:"Straw", qty:"1 straw"},
    hi:{name:"स्ट्रॉ", qty:"1 स्ट्रॉ"},
    bn:{name:"স্ট্র", qty:"১ স্ট্র"} },
  { id:"x04", cat:"extras", price:20, half:null,
    en:{name:"Mineral Water 1L", qty:"1 sealed bottle"},
    hi:{name:"मिनरल वाटर 1L", qty:"1 सील बोतल"},
    bn:{name:"মিনারেল ওয়াটার ১ লিটার", qty:"১ সিল বোতল"} },
];

export const RESORT = {
  name: "Banalata Hotel & Resort",
  address: "Forest Office, SH 2, Joypur Forest Near, Joypur, Bankura, West Bengal 722138",
  phone: "+91 97321 11701",
  gstin: "19AABCB1234C1ZQ",   // sample
  fssai: "10024055000891",    // sample
  cgstPct: 2.5,
  sgstPct: 2.5,
  serviceChargePct: 0,
  totalTables: 50,
};
